import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';

const hash=text=>createHash('sha256').update(text).digest('hex');
function excerpt(text,needle,budget=1100){const at=text.indexOf(needle);return text.slice(Math.max(0,at-100),Math.max(0,at-100)+budget);}
function docExcerpt(text,url){const readable=text.replace(/\\"/g,'"').replace(/\\n/g,'\n'),needle=url?'Source: open({"ref_id":"'+url+'"':'Give each question';return {sourceMetadataFound:readable.includes(needle),excerpt:excerpt(readable,needle,650)};}
const repairs={documentation:'Read the missing official documentation and apply its requirements before further edits.',question_design:'Split the flagged judgment, define native instructions and criteria, and retain an insufficient-evidence outcome.',evidence_preparation:'Retrieve the matching source context locally, preserve source references, and correct the evidence packet.',batching:'Batch independent questions sharing state; reuse saved results for replay.',uncertainty:'Correct confidence, missing-evidence or freshness handling; keep uncertainty visible.',reporting:'Inspect the actual application and correct the completion claim or the observed defect.'};
export function skillAuditPacket(turn,turns,example=null,priorRun=null){
  const path=new URL('../.agents/skills/typesafe-ai/SKILL.md',import.meta.url),skill=readFileSync(path,'utf8');
  const paragraphs=skill.split(/\r?\n\s*\r?\n/),pick=needle=>paragraphs.find(part=>part.includes(needle))||'';
  const rules={documentation:[pick('The live TypeSafe docs'),pick('Before writing an integration')],code_and_model:pick('Start from the behavior'),questions:[pick('Give each question'),pick('Ask one narrow'),pick('Keep the needed answers')],composition:[pick('**Ask independent'),pick('Use probabilities and confidence'),pick('Keep policy explicit')],verification:pick('Test representative cases')};
  const events=turns.filter(item=>item.fromLine<=turn.fromLine).flatMap(item=>item.events).filter(event=>event.line<=turn.toLine);
  const firstWrite=Math.min(...turn.events.filter(event=>event.kind==='tool'&&/apply_patch|Copy-Item/.test(event.text)).map(event=>event.line));
  const reads=events.filter(event=>event.line<firstWrite&&event.kind==='tool');
  const categories=['typesafe-ai','llms.txt','/api','/primitives/choice','/concepts/state','/confidence','/cookbooks/citation_check'];
  const docs=categories.map(category=>{const event=reads.filter(event=>category==='typesafe-ai'?/Get-Content/.test(event.text)&&/typesafe-ai.*SKILL/.test(event.text):/web__run/.test(event.text)&&event.text.includes('https://docs.typesafe.ai'+(category==='llms.txt'?'/llms.txt':category))).at(-1);if(!event)return {category,status:'not found'};const next=events.find(item=>item.kind==='tool-result'&&item.line>event.line),urls=event.text.match(/https:\/\/docs\.typesafe\.ai\/[a-zA-Z0-9_/.-]+/g)||[],url=urls.find(value=>value.includes(category));const text=next?.text||'';return {category,line:event.line,at:event.at,requested_url:url||null,request:category==='typesafe-ai'?excerpt(event.text,'typesafe-ai',320):url,result:next?{line:next.line,sourceTruncated:/\[\+\d+ chars\]/.test(text),...docExcerpt(text,url)}:null};});
  const writes=turn.events.filter(event=>event.kind==='tool'&&/apply_patch|Copy-Item/.test(event.text)).map(event=>({line:event.line,at:event.at,excerpt:excerpt(event.text,event.text.includes('apply_patch')?'apply_patch':'Copy-Item',350)}));
  const observed=['Editable verification workflow','actual recorded answer','4/4','HEAD -> main'].map(needle=>{const event=turn.events.filter(event=>event.kind==='tool-result'&&event.text.includes(needle)).at(-1);return event?{line:event.line,at:event.at,excerpt:excerpt(event.text,needle,needle==='Editable verification workflow'?1100:650)}:null;}).filter(Boolean);
  const definitions=[['src/verification.js','export function verificationPacket',3400],['src/workbench.js','async function runGraph',2500],['src/workbench.js','async function runOne',1900],['ui/workflow-studio.js','function light()',2700],['ui/workflow-studio.js','async function run()',1000],['ui/workflow-studio.js','function play()',650]];
  const implementation=definitions.map(([file,needle,budget])=>{const text=readFileSync(new URL('../'+file,import.meta.url),'utf8');return {file,sha256:hash(text),excerpt:excerpt(text,needle,budget)};});
  const claim=turn.events.filter(event=>event.kind==='assistant').at(-1)?.text.split(/\n\s*\n/)[0]||'';
  const calls=priorRun?.steps?.flatMap(step=>step.results||[])||[];
  const state={review_goal:'Check whether Codex followed the TypeSafe skill during the selected implementation turn and in the current code. Historical actions remain historical; a corrected current file does not rewrite the chat log.',claim,skill:{name:'typesafe-ai',sha256:hash(skill),rules},turn:{id:turn.id,fromLine:turn.fromLine,toLine:turn.toLine},documentation_reads:docs,recorded_verification:example?{resultId:example.id,turnId:example.turnId,request:{state:example.verification?.state,questions:example.questions},response:example.rawResponse}:null,batching_observation:priorRun?{storedRunId:priorRun.id,nodeCount:priorRun.steps.length,uniqueResultIds:[...new Set(calls.map(call=>call.id))],uniqueGatewayCallIds:[...new Set(calls.map(call=>call.callId))],questionIds:Object.keys(calls[0]?.questions||{}),note:'These are local stored request identifiers and question definitions, not prior model judgments used as truth.'}:null,implementation_actions:writes.slice(0,3),implementation,observed_results:observed,repair_instructions:repairs,limitations:'This is a bounded audit of retrieved records and current source. An omitted proof must yield insufficient_evidence. A positive result asks the user for behavioral review; it is not proven general accuracy.'};
  const finalAnswer=turn.events.filter(event=>event.kind==='assistant').at(-1)?.text||'';
  const code=needle=>implementation.find(item=>item.excerpt.includes(needle));
  const focused={review_goal:state.review_goal,claim,skill:{name:state.skill.name,sha256:state.skill.sha256},turn:state.turn,checks:{
    documentation:{rules:rules.documentation,documentation_reads:docs,first_implementation_action:writes[0]},
    question_design:{rules:rules.questions,recorded_native_questions:example?.questions},
    evidence_preparation:{rules:[rules.code_and_model,rules.questions],recorded_native_state:example?.verification?.state,retrieval_source:code('verificationPacket')},
    batching:{rules:rules.composition[0],source:code('async function runGraph'),replay_source:code('function play()'),execution:state.batching_observation},
    uncertainty:{rules:[rules.composition[1],rules.composition[2]],light_source:code('function light()'),recorded_raw_answer:example?.rawResponse?.answers,source_coverage:{missingEvidence:example?.verification?.missingEvidence,truncatedSource:example?.verification?.truncatedSource,quoteFound:example?.verification?.quoteFound}},
    reporting:{rules:rules.verification,assistant_statements:finalAnswer.split(/\n\s*\n/).filter(part=>!part.startsWith('![')),observations:observed,recorded_call:{id:example?.id,model:example?.answeredBy,rawResponse:example?.rawResponse}}
  },repair_instructions:repairs,limitations:state.limitations};
  // Known schema, counts and ordering are checked locally; Jev judges their meaning.
  focused.checks.documentation.documentation_reads=docs.map(({category,line,at,requested_url,result})=>({category,line,at,requested_url,result_line:result?.line,sourceMetadataFound:result?.sourceMetadataFound,source_excerpt:result?.excerpt.slice(0,350)}));
  focused.checks.question_design.rules=rules.questions.slice(0,2);
  focused.checks.evidence_preparation.rules=[rules.code_and_model,rules.questions[0]];
  focused.checks.evidence_preparation.retrieval_source={file:'src/verification.js',sha256:implementation[0].sha256,observed_request_scope:example?.scope,actual_state_keys:Object.keys(example?.verification?.state||{}),retrieval_method:example?.verification?.state?.retrieval,recorded_source_quote:example?.verification?.state?.evidence?.[0]?.excerpt};
  focused.checks.batching.source={file:'src/workbench.js',sha256:code('async function runGraph')?.sha256,cache_definition:code('async function runGraph')?.excerpt.split('\n').filter(line=>line.includes('grouped')||line.includes('evaluate({')).join('\n')};
  focused.checks.uncertainty.light_source={file:'ui/workflow-studio.js',sha256:code('function light()')?.sha256,exact_function:code('function light()')?.excerpt.split('const badge=')[0]};
  focused.checks.reporting.observations=observed.map(item=>({...item,excerpt:item.excerpt.slice(0,item.excerpt.includes('Editable verification workflow')?700:400)}));
  const evidence=[...docs.map(item=>({line:item.line,name:'Documentation read',excerpt:JSON.stringify(item)})),...implementation.map(item=>({name:item.file,excerpt:item.excerpt,sha256:item.sha256}))];
  return {mode:'typesafe-skill',state:focused,evidence,claims:[],bytes:JSON.stringify(focused).length,missingEvidence:docs.some(item=>!item.result),truncatedSource:false,quoteFound:true};
}
