(() => {
  'use strict';
  window.WorkflowStudio=function(ctx){
    const {h,button,select,option,field,api,lib,root}=ctx;
    let selected='source',tab='conversation',dockTab='activity',dockOpen=false,inspectorOpen=true,dispose=null,graphApi=null,runs=[],active=null,packet=null,claim='',busy=false,message='',step=0,timer=null,undo=[],redo=[],loadedKey='',saved='';
    const w=()=>ctx.workflow(),verify=()=>w()?.graph?.nodes.some(node=>node.questionId==='relation'),icon=name=>{const el=h('img',undefined,'studio-icon');el.src=window.WorkflowIcons?.[name+'-light']||`/_/ui/vendor/icons/${name}-light.svg`;el.alt='';return el;};
    const ib=(name,label,fn,cls='')=>{const el=button('',fn,'studio-icon-button '+cls);el.append(icon(name));el.title=label;el.setAttribute('aria-label',label);return el;};
    const say=(text,error=false)=>{message=text;ctx.notice(text,error);const el=root.querySelector('.studio-status-message');if(el)el.textContent=text;};
    const snapshot=()=>{undo.push(JSON.stringify(w()));undo=undo.slice(-30);redo=[];};
    const change=fn=>{snapshot();fn();active=null;render();};
    const menu=(name,items)=>{const el=h('details',undefined,'studio-menu');el.append(h('summary',name));const box=h('div',undefined,'studio-menu-items');for(const [label,fn] of items)box.append(button(label,()=>{el.open=false;fn();}));el.append(box);return el;};
    const label=node=>node.id==='source'?'Assistant turn':node.id==='lookup'?'Retrieve source passages':node.kind==='agent'?`${ctx.agents().find(a=>a.id===node.agentId)?.name||'Classifier'} · ${node.questionId}`:node.kind==='gate'?node.op.toUpperCase():node.id==='source'?'Assistant turn':node.id==='lookup'?'Retrieve source passages':'Final decision';
    const nodes=()=>w().graph?.nodes||[...(w().steps||[]).map((s,i)=>({id:String(i),kind:'agent',...s,questionId:'all questions'})),{id:'out',kind:'output'}];
    const edges=()=>w().graph?.edges||nodes().slice(1).map((node,i)=>({source:nodes()[i].id,target:node.id}));
    const result=()=>active?.steps?.flatMap(item=>item.results||[]).find(item=>item.rawResponse?.answers?.relation);
    function light(){
      if(!active)return {tone:'neutral',label:'Not checked',glyph:'●'};
      if(!active.complete)return {tone:'neutral',label:'Call failed',glyph:'●'};
      if(verify()){const r=result(),a=r?.rawResponse?.answers?.relation,p=r?.verification;
        if(!a||a.choice==='says_nothing'||(a.confidence??0)<0.8)return {tone:'neutral',label:'Uncertain',glyph:'●'};
        if(a.choice==='contradicts')return {tone:'red',label:'Claim contradicted',glyph:'●'};
        if(!p||p.missingEvidence||p.truncatedSource||!p.quoteFound)return {tone:'neutral',label:'Evidence gap',glyph:'●'};
        return {tone:'green',label:'Claim supported',glyph:'●'};
      }
      const output=active.trace?.output,values=Object.values(active.trace?.nodes||{}),uncertain=values.some(item=>item.kind==='agent'&&item.answer?.confidence!==undefined&&item.answer.confidence<0.8);
      if(output===null||output===undefined||uncertain)return {tone:'neutral',label:'Uncertain',glyph:'●'};
      const issues=nodes().some(node=>['fail','wrong_track','avoided','contradicts'].includes(node.predicate?.option));
      const pass=issues?!output:!!output;return {tone:pass?'green':'red',label:pass?'Pass':'Issue detected',glyph:'●'};
    }
    const badge=()=>{const s=light(),el=h('span',s.glyph+' '+s.label,'studio-verdict '+s.tone);el.setAttribute('role','status');return el;};
    async function load(){const key=w().id+'|'+ctx.session()+'|'+ctx.turn()?.id;if(key===loadedKey)return;loadedKey=key;packet=null;active=null;claim='';step=0;clearInterval(timer);timer=null;
      try{if(w().id){runs=(await api(`/api/workflows/${w().id}/runs?session=${encodeURIComponent(ctx.session())}`)).runs;active=runs.find(run=>run.turnId===ctx.turn()?.id)||null;}
        if(verify()&&ctx.turn()){const prior=result()?.verification;packet=prior||await api('/api/verification/pack',{sessionId:ctx.session(),turnId:ctx.turn().id});claim=packet.state.claim;}
        if(ctx.workflow()?.id+'|'+ctx.session()+'|'+ctx.turn()?.id===key)render();
      }catch(error){say(error.message,true);}
    }
    async function prepare(value){claim=value;active=null;try{packet=await api('/api/verification/pack',{sessionId:ctx.session(),turnId:ctx.turn().id,claim});tab='evidence';render();}catch(error){say(error.message,true);}}
    async function save(){try{ctx.setWorkflow(await api('/api/workflows',w()));await ctx.refreshWorkflows();saved=JSON.stringify(w());say('Workflow saved.');render();}catch(error){say(error.message,true);}}
    async function run(){if(busy||!ctx.turn()?.complete)return;if(JSON.stringify(w())!==saved){say('Save your workflow changes before running Jev.',true);return;}busy=true;render();try{active=await api(`/api/workflows/${w().id}/run`,{sessionId:ctx.session(),turnId:ctx.turn().id,scope:verify()?'verification':'turn',...(verify()?{claim}: {})});runs=[active,...runs];ctx.onRun(active);dockOpen=true;dockTab='activity';say(active.complete?'Jev judgment saved. Replay uses this saved answer.':active.error||'Run failed.',!active.complete);}catch(error){say(error.message,true);}finally{busy=false;render();}}
    const stages=()=>[...(verify()?['source','lookup']:[]),...nodes().map(n=>n.id)];
    function play(){if(timer){clearInterval(timer);timer=null;render();return;}step=0;timer=setInterval(()=>{step++;selected=stages()[Math.min(step,stages().length-1)];if(step>=stages().length-1){step=stages().length-1;clearInterval(timer);timer=null;}render();},1600);render();}
    async function addAgent(){const id=ctx.agents()[0]?.id;if(!id){say('Create a classifier in Agents first.');return;}const agent=await api('/api/agents/'+id),q=(await api('/api/agents/validate',{source:agent.revisions.find(r=>r.id===agent.activeRevisionId).source})).questions,[questionId,question]=Object.entries(q)[0];change(()=>{if(!w().graph){w().steps.push({agentId:id,revisionId:agent.activeRevisionId});return;}const g=w().graph,node={id:'check_'+Date.now(),kind:'agent',agentId:id,revisionId:agent.activeRevisionId,questionId,predicate:question.type==='choice'?{type:'choice',option:Object.keys(question.criteria)[0],abstainOptions:Object.keys(question.criteria).filter(k=>/insufficient|nothing|unsupported/.test(k))}:{type:question.type,threshold:question.type==='noul'?0.5:1},assumption:{sensitivity:0.8,specificity:0.9}};g.nodes.push(node);const prior=g.edges.find(e=>e.target===g.outputId),gate=g.nodes.find(n=>n.id===prior?.source&&n.kind==='gate'&&n.op!=='not');if(gate)g.edges.push({source:node.id,target:gate.id});else{const gateId='gate_'+Date.now();g.nodes.push({id:gateId,kind:'gate',op:'and'});g.edges=g.edges.filter(e=>e!==prior);if(prior)g.edges.push({source:prior.source,target:gateId});g.edges.push({source:node.id,target:gateId},{source:gateId,target:g.outputId});}selected=node.id;tab='settings';});}
    function choose(id){clearInterval(timer);timer=null;const found=ctx.workflows().find(item=>item.id===id);if(found){ctx.setWorkflow(structuredClone(found));saved=JSON.stringify(w());loadedKey='';active=null;packet=null;ctx.render();}}
    function toolbar(){const bar=h('header',undefined,'studio-toolbar'),crumb=h('div',undefined,'studio-breadcrumb'),chooseBox=select('Saved workflow');for(const item of ctx.workflows())option(chooseBox,item.id,item.name);chooseBox.value=w().id||'';chooseBox.onchange=()=>choose(chooseBox.value);crumb.append(icon('flow-arrow'),h('span','Workflows','studio-breadcrumb-parent'),chooseBox,badge());if(JSON.stringify(w())!==saved)crumb.append(h('small','Unsaved','studio-save-state'));bar.append(crumb);
      const menus=h('nav',undefined,'studio-menubar');menus.append(menu('File',[['Save workflow',save],['New gate workflow',()=>{ctx.setWorkflow({name:'New workflow',graph:{prevalence:0.2,outputId:'out',nodes:[{id:'out',kind:'output'}],edges:[]},positions:{}});loadedKey='';render();}],['New ordered workflow',()=>{ctx.setWorkflow({name:'Ordered workflow',steps:[],positions:{}});loadedKey='';render();}],['Tool routing',()=>{ctx.setWorkflow(ctx.newRoute());ctx.render();}]]),menu('Edit',[['Undo',()=>{if(undo.length){redo.push(JSON.stringify(w()));ctx.setWorkflow(JSON.parse(undo.pop()));render();}}],['Redo',()=>{if(redo.length){undo.push(JSON.stringify(w()));ctx.setWorkflow(JSON.parse(redo.pop()));render();}}],['Add classifier',addAgent],['Graph definition / connections',()=>{tab='settings';selected='workflow';render();}]]),menu('View',[['Conversation',()=>{tab='conversation';inspectorOpen=true;render();}],['Evidence sent to Jev',()=>{tab='evidence';inspectorOpen=true;render();}],['Fit canvas',()=>graphApi?.fitView({padding:0.15})],['Toggle inspector',()=>{inspectorOpen=!inspectorOpen;render();}]]),menu('Workflow',[['Run selected claim',run],['Saved run history',()=>{dockTab='history';dockOpen=true;render();}],['Projection and metrics',()=>{tab='metrics';render();}]]));bar.append(menus);
      const actions=h('div',undefined,'studio-toolbar-actions');actions.append(ib('floppy-disk','Save workflow',save),ib('file-text','Show conversation',()=>{tab='conversation';inspectorOpen=true;render();}),ib('eye','Inspect evidence',()=>{tab='evidence';inspectorOpen=true;render();}),ib('play','Run Jev verification',run,'studio-primary'),ib('dots-three','Workflow settings',()=>{selected='workflow';tab='settings';render();}));actions.querySelector('[aria-label="Run Jev verification"]')?.toggleAttribute('disabled',busy||!w().id||!ctx.turn()?.complete||JSON.stringify(w())!==saved);bar.append(actions);root.append(bar);}
    function canvas(center){const displayNodes=[...(verify()?[{id:'source',kind:'gate',op:'SOURCE'},{id:'lookup',kind:'gate',op:'LOOKUP'}]:[]),...nodes()],displayEdges=[...(verify()?[{source:'source',target:'lookup'},{source:'lookup',target:nodes().find(n=>n.kind==='agent')?.id}]:[]),...edges()];
      const positions={...Object.fromEntries(displayNodes.map((node,i)=>[node.id,{x:40+(i%3)*290,y:70+Math.floor(i/3)*210}])),...(w().positions||{})},graph=h('div',undefined,'studio-canvas');graph.setAttribute('aria-label','Editable verification workflow');center.append(graph);
      dispose=lib.workflowGraph(graph,{nodes:displayNodes,edges:displayEdges},positions,{colorMode:'dark',selected:timer?stages()[step]:selected,ready:instance=>graphApi=instance,label,presentation:node=>{const trace=active?.trace?.nodes?.[node.id],a=trace?.answer;return {title:label(node),kind:node.id==='source'?'LOCAL · CODEX TRANSCRIPT':node.id==='lookup'?'LOCAL · SOURCE LOOKUP':node.kind==='agent'?'JEV · CHOICE':node.kind==='gate'?'LOCAL · LOGIC':'VERIFICATION RESULT',icon:node.id==='source'?'file-text':node.id==='lookup'?'eye':node.kind==='agent'?'intersect':node.kind==='gate'?'tree-structure':'shield-check',tone:node.kind==='output'?light().tone:node.id==='source'?'blue':node.id==='lookup'?'amber':'violet',status:node.id==='source'?ctx.turn()?'Loaded':'No turn':node.id==='lookup'?packet?`${packet.state.evidence.length} passages`:'Not prepared':a?a.choice||String(a.noul):node.kind==='output'?light().label:trace?String(trace.value):'Not run'};},move:(id,pos)=>{snapshot();w().positions||={};w().positions[id]=pos;},inspect:id=>{selected=id;tab=id==='source'?'conversation':id==='lookup'?'evidence':'settings';inspectorOpen=true;render();},connect:edge=>{if(w().graph)change(()=>w().graph.edges.push(edge));},disconnect:edge=>{if(w().graph)change(()=>w().graph.edges=w().graph.edges.filter(e=>e.source!==edge.source||e.target!==edge.target));}});}
    function conversation(body){const turn=ctx.turn(),chooseBox=select('Conversation turn');for(const t of [...ctx.turns()].reverse().filter(t=>t.complete))option(chooseBox,t.id,`${new Date(t.at).toLocaleTimeString()} · ${(t.events.find(e=>e.kind==='user')?.text||'Turn').replace(/<in-app-browser-context[\s\S]*?<\/in-app-browser-context>/g,'').replace(/## My request:/g,'').trim().slice(0,60)}`);chooseBox.value=turn?.id||'';chooseBox.onchange=()=>{ctx.setTurn(ctx.turns().find(t=>t.id===chooseBox.value));loadedKey='';render();};if(!turn){body.append(h('p','No completed answer in this conversation.'));return;}const answer=turn.events.filter(e=>e.kind==='assistant').at(-1),messageBox=h('article',undefined,'studio-chat'),text=answer?.text||'';messageBox.append(h('strong','Codex · actual recorded answer'),h('div',text.split(/\n\s*\n/)[0].replace(/\*\*/g,'')));const full=h('details');full.append(h('summary','Full recorded answer'),h('pre',text),h('small',turn.id));messageBox.append(full);body.append(messageBox);if(verify()&&packet){const box=select('Claim to verify');for(const [i,value] of packet.claims.entries())option(box,String(i),value.replace(/[*`]/g,'').slice(0,110));box.value=String(packet.claims.indexOf(claim));box.onchange=()=>prepare(packet.claims[Number(box.value)]);body.append(field('One verbatim claim',box),h('blockquote',claim));}body.append(field('Recorded turn',chooseBox));const request=h('details');request.append(h('summary','User request'),h('p',turn.events.find(e=>e.kind==='user')?.text));body.append(request);}
    function evidence(body){if(!packet){body.append(h('p',verify()?'Preparing evidence…':'This workflow evaluates the selected turn.'));return;}body.append(h('strong',`${packet.bytes.toLocaleString()} characters · ${packet.state.evidence.length} selected passages`),h('blockquote',packet.state.claim),h('p','Passages retain their source lines. Retrieval is lexical; check context before trusting a positive judgment.'));
      for(const e of packet.state.evidence){const item=h('details');item.open=true;item.append(h('summary',`${e.name||'Tool result'} · L${e.line}${e.sourceTruncated?' · source truncated':''}`),h('pre',e.excerpt));body.append(item);}if(!packet.state.evidence.length)body.append(h('p','No matching source evidence. The light cannot turn green.'));const raw=h('details');raw.append(h('summary','Exact state sent to Jev'),h('pre',JSON.stringify(packet.state,null,2)));body.append(raw);}
    async function settings(body){const node=nodes().find(n=>n.id===selected);if(selected==='workflow'||!node){const name=h('input');name.value=w().name;name.setAttribute('aria-label','Workflow name');name.onchange=()=>w().name=name.value;body.append(field('Name',name));const json=h('textarea');json.rows=16;json.value=JSON.stringify(w().graph||w().steps,null,2);json.setAttribute('aria-label','Workflow definition');body.append(field(w().graph?'Nodes, predicates and connections':'Ordered steps',json),button('Apply definition',()=>{try{change(()=>{const value=JSON.parse(json.value);if(w().graph)w().graph=value;else w().steps=value;});}catch(e){say(e.message,true);}}),button('Add classifier',addAgent),button('Save workflow',save));return;}
      body.append(h('h3',label(node)));if(node.kind==='agent'){const agents=select('Node classifier');for(const a of ctx.agents())option(agents,a.id,a.name);agents.value=node.agentId;agents.onchange=async()=>{const a=await api('/api/agents/'+agents.value),q=(await api('/api/agents/validate',{source:a.revisions.find(r=>r.id===a.activeRevisionId).source})).questions,[id,value]=Object.entries(q)[0];change(()=>{node.agentId=a.id;node.revisionId=a.activeRevisionId;if(!w().graph)Object.assign(w().steps[Number(node.id)],{agentId:a.id,revisionId:a.activeRevisionId});node.questionId=id;node.predicate=value.type==='choice'?{type:'choice',option:Object.keys(value.criteria)[0],abstainOptions:Object.keys(value.criteria).filter(k=>/nothing|insufficient/.test(k))}:{type:value.type,threshold:0.5};});};body.append(field('Classifier',agents));
        try{const agent=await api('/api/agents/'+node.agentId),revision=agent.revisions.find(r=>r.id===node.revisionId),qs=(await api('/api/agents/validate',{source:revision.source})).questions;if(!body.isConnected)return;const qselect=select('Jev question');for(const [id,q] of Object.entries(qs))option(qselect,id,id+' · '+q.type);qselect.value=node.questionId;qselect.onchange=()=>change(()=>{const q=qs[qselect.value];node.questionId=qselect.value;node.predicate=q.type==='choice'?{type:'choice',option:Object.keys(q.criteria)[0],abstainOptions:Object.keys(q.criteria).filter(k=>/nothing|insufficient/.test(k))}:{type:q.type,threshold:0.5};});body.append(field('Question',qselect),h('pre',JSON.stringify(qs[node.questionId],null,2)));}catch(error){body.append(h('p',error.message));}
      }
      const json=h('textarea');json.rows=8;json.value=JSON.stringify(node,null,2);json.setAttribute('aria-label','Node definition');body.append(field('Pinned revision, predicate and assumptions',json),button('Apply node',()=>{try{const value=JSON.parse(json.value);change(()=>{if(w().graph)Object.assign(node,value);else Object.assign(w().steps[Number(node.id)],{agentId:value.agentId,revisionId:value.revisionId});});}catch(e){say(e.message,true);}}));if(node.kind!=='output')body.append(button('Remove node',()=>change(()=>{if(w().graph){w().graph.nodes=w().graph.nodes.filter(n=>n!==node);w().graph.edges=w().graph.edges.filter(e=>e.source!==node.id&&e.target!==node.id);}else w().steps.splice(Number(node.id),1);})));}
    function inspector(){if(!inspectorOpen)return;const panel=h('aside',undefined,'studio-inspector');panel.setAttribute('aria-label','Workflow inspector');const head=h('header',undefined,'studio-inspector-head');head.append(icon('sliders-horizontal'),h('h2',tab==='conversation'?'Conversation':tab==='evidence'?'Source evidence':tab==='metrics'?'Measurements':'Node inspector'),ib('x','Close inspector',()=>{inspectorOpen=false;render();}));panel.append(head);const tabs=h('nav',undefined,'studio-inspector-tabs');for(const [id,title] of [['conversation','Turn'],['evidence','Evidence'],['settings','Settings']]){const b=button(title,()=>{tab=id;render();});b.setAttribute('aria-selected',String(tab===id));tabs.append(b);}panel.append(tabs);const body=h('div',undefined,'studio-inspector-body');panel.append(body);if(tab==='conversation')conversation(body);else if(tab==='evidence')evidence(body);else if(tab==='metrics'){if(w().graph)api('/api/workflows/project',{graph:w().graph}).then(data=>body.append(h('h3','Illustrative projection'),h('pre',JSON.stringify(data,null,2)))).catch(e=>say(e.message,true));if(w().id)api(`/api/workflows/${w().id}/metrics?session=${ctx.session()}`).then(data=>body.append(h('h3','Saved measurements'),h('pre',JSON.stringify(data,null,2)))).catch(e=>say(e.message,true));}else void settings(body);return panel;}
    function dock(){const panel=h('section',undefined,'studio-dock'+(dockOpen?' is-expanded':'')),bar=h('nav',undefined,'studio-dock-tabs');for(const [id,title,name] of [['activity','Activity','pulse'],['evidence','Evidence','file-text'],['history','History','clock-counter-clockwise']]){const b=button('',()=>{dockOpen=id===dockTab?!dockOpen:true;dockTab=id;render();});b.append(icon(name),h('span',title));bar.append(b);}if(active){const playButton=button(timer?'Pause':'Play',play);playButton.setAttribute('aria-label',timer?'Pause replay':'Play replay');bar.append(playButton);const range=h('input');range.type='range';range.min='0';range.max=String(stages().length-1);range.value=String(step);range.setAttribute('aria-label','Replay step');range.oninput=()=>{clearInterval(timer);timer=null;step=Number(range.value);selected=stages()[step];render();};bar.append(range,h('span',`${step+1}/${stages().length}`));}bar.append(ib(dockOpen?'caret-down':'caret-up',dockOpen?'Collapse activity':'Expand activity',()=>{dockOpen=!dockOpen;render();}));panel.append(bar);const body=h('div',undefined,'studio-dock-body');if(dockTab==='history'&&dockOpen){for(const r of runs)body.append(button(`${new Date(r.at).toLocaleString()} · ${r.turnId}`,()=>{active=r;const prior=result()?.verification;if(prior){packet=prior;claim=prior.state.claim;}step=0;render();}));}else if(dockTab==='evidence'&&dockOpen){if(active)body.append(h('pre',JSON.stringify(result()?.rawResponse||active.steps,null,2)));else body.append(h('p','No Jev response yet.'));}else{body.append(badge(),h('span',active?`${label(nodes().find(n=>n.id===stages()[step])||{id:stages()[step]})} · saved run ${active.id.slice(0,8)}`:'Choose one claim, inspect its evidence, then run Jev.'));if(verify()&&result()){const text=result().verification.state.claim.replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[*]/g,'');body.append(h('span','Checked claim: '+text,'studio-selected-claim'));}if(dockOpen&&result()){const r=result(),a=r.rawResponse.answers.relation;body.append(h('span',`Jev: ${a.choice} · confidence ${a.confidence} · ${r.usage?.input_tokens||0} input tokens`));}}panel.append(body);root.append(panel);}
    function render(){if(!saved&&w().id)saved=JSON.stringify(w());dispose?.();dispose=null;root.onfocusin=root.oninput=root.onchange=null;root.replaceChildren();root.classList.add('workflow-studio','tool-routing-page');document.body.classList.add('workflow-studio-active');toolbar();const workspace=h('div',undefined,'studio-workspace row g-0'),rail=h('nav',undefined,'studio-rail');rail.append(ib('cursor','Select node',()=>say('Select a node to edit it.')),ib('plus','Add classifier',addAgent),ib('tree-structure','Arrange workflow',()=>change(()=>w().positions={})),ib('file-text','Conversation',()=>{tab='conversation';inspectorOpen=true;render();}),ib('clock-counter-clockwise','Run history',()=>{dockTab='history';dockOpen=true;render();}),ib('sliders-horizontal','Edit workflow',()=>{selected='workflow';tab='settings';inspectorOpen=true;render();}));workspace.append(rail);const center=h('section',undefined,'studio-stage col');canvas(center);workspace.append(center);const side=inspector();if(side)workspace.append(side);root.append(workspace);dock();const footer=h('footer',undefined,'studio-status');footer.append(h('span',message||'One claim + matching source passages. No automatic paid calls.','studio-status-message'),h('span','Confidence threshold 0.80 · provisional'));root.append(footer);if(loadedKey!==w().id+'|'+ctx.session()+'|'+ctx.turn()?.id)void load();}
    return {render,setViewing:visible=>{if(!visible){clearInterval(timer);timer=null;}}};
  };
})();
